# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create username: 'Boomy', email: 'boomy@doggy.com', password_digest: BCrypt::Password.create("boomy")
User.create username: 'Goku', email: 'goku@saiyan.com', password_digest: BCrypt::Password.create("goku")
User.create username: 'Elliot', email: 'elliot@hacker.com', password_digest: BCrypt::Password.create("elliot")
User.create username: 'Anakin', email: 'anakin@starwars.com', password_digest: BCrypt::Password.create("anakin")

Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Boomy', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Goku', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Elliot', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Anakin', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Boomy', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Goku', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Elliot', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Elliot', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Anakin', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Boomy', created_at: Faker::Time.backward(1500, :evening)
Post.create unique_id: SecureRandom.uuid, title: Faker::StarWars.quote, content: Faker::Lorem.paragraph(16), username: 'Anakin', created_at: Faker::Time.backward(1500, :evening)

Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Boomy', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Goku', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Goku', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Elliot', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Boomy', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Anakin', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Goku', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Boomy', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Boomy', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Elliot', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Anakin', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Goku', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Anakin', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Boomy', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Elliot', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Goku', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Anakin', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Anakin', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Elliot', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Elliot', created_at: Faker::Time.backward(800, :evening)
Comment.create unique_id: SecureRandom.uuid, post_id: Faker::Number.between(1, 11), content: Faker::Hacker.say_something_smart, username: 'Elliot', created_at: Faker::Time.backward(800, :evening)
